### ISSUE TITLE
Ranking Filter Issue

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#12]
When using the ranking filter, I was stuck and confused on how to use it for a bit. Originally, I thought that the Lower and Upper boxes were suppose to be lower and upper bounds. For example, I thought that if I put 10 in the Lower box, that all colleges ranked 10 and above would show up, but instead the colleges ranked 10-10000 showed up (vice versa for Upper box). Unlike the other filters that require numbers, the rankings filter was much less intuitive.

I think it would be better to write in "Lower Bound" and "Upper Bound" on the boxes and/or have like a small question mark button that tells you how each filter works.

**Comment by keskinmbaha** [comment]
New update still doesn't address this issue. Lower bound box does not filter the rankings by removing anything below the lower bound. Again, if I put in 10 in the lower bound, I would expect colleges ranked 1-10 to show up by instead colleges ranked 10-Unranked show up.

**Comment by amiteshksharma** [comment]
Well, the point of the question box is to explain how it works. What you expect doesn't necessarily mean I should change the design just yet... if there are multiple cases then I will look into it. My question to you is, did the question marks help clarify how to use the ranking filter? The point of the questions is to help clarify how to use the filters when users, like yourself, are confused. I would also say it could possibly be worse for the user if the ranking range worked differently than the rest of the input fields...

**Comment by gmihir** [comment]
Yeah, I agree with Amitesh. Rankings are weird because lower is "better," but it doesn't make sense to have one filter sort differently than the other. And to me and a few others I've asked, it's more intuitive to have 10 as a lower bound show 10+, not 1-10.

**Comment by keskinmbaha** [comment]
I understand what you guys ares saying to keep it consistent, but to comment to you Mihir, I asked a few people as well and they thought similar to what I was thinking. Because college rankings are different in that a lower number means a higher ranking, I (and the people I talked with) thought that a lower bound would mean that colleges ranked lower (i.e. higher numbers) would be excluded.

**Comment by amiteshksharma** [comment]
You didn't answer my question. did the question mark help you understand, or if it didn't, do you think if it was worded properly it would help?

**Comment by keskinmbaha** [comment]
Ah forgot to answer that. For the other filters I instantly got it so I understood how the filter was suppose to work. But the Ranking filter it still took me a few seconds to comprehend that it was filtering by number not by ranking. It might be better to give 2 examples. One for just lower bound and one for just upper bound.

**Comment by keskinmbaha** [comment]
Since there will be some people that either want ranking filter your guys way and some people want a ranking filter my way, it makes sense to leave it right now since our best solution was to add the information button. If we do find a better solution, then we can implement, but for now I'm going to mark this as a low priority bug.

**Comment by keskinmbaha** [comment]
Put this issue in the low priority issue thread. Closing this issue.
