### ISSUE TITLE
Letters of Rec Filter No Longer Works

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#13]
It was annoying it constantly click on the apply filters button each time I wanted to add a filter. Might be better for the user to instead have to only press enter instead for the boxes and for the drop down menus just clicking the filter option would be easier as well.

**Comment by amiteshksharma** [comment]
I added a listener for the "enter" key on all text field inputs. All dropdowns will search when clicking an option. No necessity for the apply button unless a user feels it necessary for themselves, so the button will stay there. We may have to consider if we want to get rid of it just to limit the number of calls to the backend database... but that depends on how many users, and the amount in the database.

**Comment by keskinmbaha** [comment]
The enter key still doesn't work. I did some small testing with the drop downs and for some reason it seems like the letters of rec drop down does not work. All the other drop downs do work for now. Also, a small bug is that when choosing Alaska in the drop down causes NAU to show up even though it is Arizona university.

**Comment by keskinmbaha** [comment]
Filtering by letters of rec works now. This issue is resolved.
