### ISSUE TITLE
Putting Doubles in Filters

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#15]
I can input doubles and apply filters, but no colleges show up when using doubles. An exception for this is Tulane and St. John's University since both of these colleges have app fees of $0 (doesn't matter the double number, either way inputting a double into the app fee filter causes these two colleges to show up.

**Comment by amiteshksharma** [comment]
if you put a double, a random letter, or anything besides 0-9 digits, it should render no tiles at all. Try all random characters to make sure it works.

**Comment by amiteshksharma** [comment]
UPDATE: App fee takes in a double now, and all the other input fields take all characters, but if they are not [0-9] then it will return nothing, except app fee, which will take periods for doubles.
