### ISSUE TITLE
Bug With State Filtering When Going to Dashboard and Back

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#19]
When you add a one or more states to the filter and remove it using remove all then click dashboard then click back on the explore page, a state box with no state name shows up in the state filter. Similar to the one state filter bug, you can only remove it by clicking on the remove all states filter button.

**Comment by amiteshksharma** [comment]
There should be no empty tag in the state filter now... make sure that's true but I will close this issue for now,
