### ISSUE TITLE
National ranking on Explore Page when Unranked

### ISSUE THREAD

**Issue by gmihir** [ashwinxkumar01/apps-college#2]
Explore page shows national ranking on tiles, but shows incorrect value for unranked colleges since they are stored as high numbers in the database to facilitate sorting.

**Comment by amiteshksharma** [comment]
What should be put instead of 10000, should it be "n/a"? Another concern my brother mentioned is we should have an average from multiple sites to have better numbers and more accurate representations of the ranking.

**Comment by gmihir** [comment]
I think just having an if national ranking > 400 or some high number we know that it's not an actual ranking and then showing "Unranked" should work. We can look into using different sources for rankings, but I don't know how we would resolve ties or some colleges being ranked on some sources or not others. A possible solution could be to have ranking by popular majors (biology, engineering, etc.) in addition to the broader "national ranking"
