### ISSUE TITLE
Sidebar and Filters Bars Do Not Stay in Place and Instead Scroll Along with the Colleges

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#20]
As the title states and as probably others know about as well, the sidebar and the filters bar scroll along with the college nodes. As the user, it was annoying to have to scroll all the way back up in order to re-filter or go back to the dashboard or explore page.

**Comment by amiteshksharma** [comment]
I have made it so the filters follows you while scrolling. The sidebar, however, does not move with it. I think we should convert it to a horizontal navigation bar so it doesn't look janky
