### ISSUE TITLE
Wrong Button is Highlighted White

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#21]
Clicking on Dashboard then Filter or vice versa causes the wrong button to be highlighted white.

**Comment by amiteshksharma** [comment]
I'm not seeing an issue with the wrong tab being white.. I've clicked on and off, left the site and going to slickdeals and back, when going to the individual page and back,.. the tabs are highlighted correctly each time. Maybe show me on discord later tonight?

**Comment by keskinmbaha** [comment]
This is a Safari issue, so we are going to mark this as a low priority.

**Comment by keskinmbaha** [comment]
Put this issue in the low priority issue thread. Closing this issue.
