### ISSUE TITLE
Filtering by Tuition is Confusing

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#24]
I think the filtering by tuition filter could use some work. It was a bit confusing seeing only one check box for out of state tuition cause initially I was not sure if that meany if it wasn't checked that it would filter by in state and out of state or just in state. I think there should be two check boxes of some sort. One that allows for filtering only by in state and one that allows for only out of state. Not sure specifically how we could put this in. Maybe make it so that when you check on one box, you cannot check the other box and that if no box is check then it filters by both.

I definitely think there is a better way to allow filtering by tuition than the solution I gave, but currently I think that it will confuse users initially by only having one check box for out of state and only filtering by in state with checking the box.

**Comment by amiteshksharma** [comment]
Well, it goes by instate when not checked, and I guess u didnt read the I icon... anyways a better solution that I think would fit is a dropdown that you can choose between instate and out of state as two buttons would look weird imo... but then again I can also change the text depending on the state of the checkbox...

**Comment by keskinmbaha** [comment]
Well I know how it works now but what I'm saying is when I initially saw the filter it wasn't intuitive and you either had to use the information box or test yourself. I think all 3 options should be with filtering by both being the initial one with two options available for filtering by in state and out of state. But when I think about it, there is no way there is a university that has out of state lower than in state so technically filtering by out of state filters by both values. Hey maybe you can have a button similar to the "Low to High" "High to Low" button. Initially it could be on in state then when you click it it filters by out of state you know?
