### ISSUE TITLE
Drop Down Filters Title Disappears When Selecting Any

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#25]
When I select, let's say, any on the type of application filter it shows any on the drop down but there becomes no indicator that that specific drop down is the application type filter. I think that instead of displaying "any" maybe you can display the originally wording saying "Application Type".

**Comment by amiteshksharma** [comment]
It would be kind of weird to have a label called "application type" instead of any but I can look into some solution

**Comment by keskinmbaha** [comment]
True. Just wanted to point out that there is no indicator on what filter I put "Any" for.

**Comment by keskinmbaha** [comment]
We decided that this is not an issue that concerns us at the moment. When we deploy and if users point this issue out, we will fix it. For now, we can put this off to the side and think of a solution down the line.

**Comment by keskinmbaha** [comment]
Put this issue in the low priority issue thread. Closing this issue.
