### ISSUE TITLE
Nodes with titles that are two lines are mis-aligned with single line titled nodes

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#26]
As the title states, node with titles that take up two lines push all the information down one line  which becomes mis-aligned with nodes with titles that take up only one line. An example is "University of Florida".

**Comment by keskinmbaha** [comment]
Seems like a fix to this issue was made, but now tiles with titles that take up two lines cause the tiles to be enlarged and aren't the same size as the one line titled tiles.

**Comment by gmihir** [comment]
database-side fix for this issue, please verify if fixed

**Comment by keskinmbaha** [comment]
It is fixed with a standard size for my browser. Since we still have resizing issues in general, I will close this issue.
