### ISSUE TITLE
Information "i" box doesn't disappear when selecting a new "i'" or when filtering

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#27]
As the title states, when I click on the "i" for more information and then I click on another "i" or when I filter, I expected the last "i" box I clicked to disappear but it doesn't and instead I have to manually click it again to remove the box that popped up.

**Comment by amiteshksharma** [comment]
Have you tested recently? Andrew and I addressed this issue.. and it worked on my end so try pulling and testing it

**Comment by keskinmbaha** [comment]
Yup, I had this issue queued up so I just pushed it before checking the latest pull. It works now. Thanks and closing this bug.
