### ISSUE TITLE
Top menu bar no longer highlights the page you are on white + wrong button highlighted

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#29]
When I click on Explore page, the "Explore" button on the tab bar is not highlighted white. Same thing with dashboard when I login for the first time and when clicking on it from the explore page. Only time these buttons are highlighted white are when I click back a page on my browser and the problem with this is is that the wrong button becomes highlighted. If I go back to explore, dashboard is highlighted white and vice versa.

**Comment by amiteshksharma** [comment]
The navbar is being dealt with... maybe hold off on any issues for that until I say I'm done with it
