### ISSUE TITLE
Check Box Issues on Dashboard

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#31]
People already know this issue, but just wanted to have it in the issues tab that the checkbox is already marked with a blue checkmark even when there are no colleges in the dashboard.

**Comment by keskinmbaha** [comment]
Also, not sure with the latest push but the 'all' checkbox on the dashboard is not lined up with the checkboxes of the individual colleges on the dashboard.

**Comment by skaiwu** [comment]
I'll get to it should be done by tomorrow

**Comment by keskinmbaha** [comment]
Also, do not know if you knew this but if you click on the check box to select everything and you click on it again to uncheck everything, it does not unselect everything.

**Comment by skaiwu** [comment]
done
