### ISSUE TITLE
Can Still Filter by Tuition Even When Nothing From the Drop Down is Selected

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#34]
As title states, you can still filter by tuition even though there is nothing selected from the drop box. Not sure if this what was intended but based on what is available on the drop downs, it doesn't make sense to filter by tuition if nothing from the drop is not selected.

**Comment by amiteshksharma** [comment]
If a tuition is stated in the text boxes, the default will be both in state and out of state tuition being displayed. If nothing is inputed into the textboxes, then it would filter by tuition at all... the two are not connected at the moment.. and I think it's ok to keep this way

**Comment by keskinmbaha** [comment]
So if the user gives a tuition amount, then the default filter is by both in and out of state, and like you said if nothing is inputted it is not filtered by tuition. I know you said that the two tuition filters do not need to be connected at the moment, but can you make it (without too much effort) so that the drop down will display both when the user inputs and filters by tuition amount without having selected anything from the drop down? That way the user understands it will filter by both automatically.

Also, the information icon still includes text about the check box, even thought there is no check box anymore. Might want to update it sometime.

**Comment by keskinmbaha** [comment]
Issue is resolved. Closing the issue.
