### ISSUE TITLE
Problem With Acceptance Rate Filter

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#36]
I know that you can enter a decimal for acceptance rate but if you enter more than one decimal (or dot) in the acceptance filter, than the filters page doesn't show an error even though it should not be accepting more than one decimal point.

**Comment by amiteshksharma** [comment]
I also fixed this, I will push it soon and tell you when its pushed

**Comment by keskinmbaha** [comment]
Issue is fixed. Closing Issue.
