### ISSUE TITLE
Clear Filters Problem

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#37]
On the filters page, if I have some filters and I decide to clear the filters, everything clears as expected. But, if I click on dashboard or the essay tab and then click back on the explore page, the filters that I just cleared have re-appeared.

**Comment by amiteshksharma** [comment]
Im gonna push a fix for this soon, test it out when I tell u its done

**Comment by keskinmbaha** [comment]
Issue is fixed. Closing issue.
