### ISSUE TITLE
Hearting Colleges Problem When Filtering

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#43]
There are multiple problems that seem to stem from one issue and I will list all the problems one by one.

1. I use the filters to find a college. I heart it. I then click on the essays tab. When I quick search the same college the college is no longer hearted. I then click back on the explore page. Since the filters are suppose to stay there, I see the college I hearted there, but it is no longer hearted. If I repeat these exact same steps back to back on the same college, the problem is gone. Also to note, if instead of going to the essays tab I go to the dashboard, there is no problem (i.e. the college is hearted) IF my colleges list loads. IF the colleges list does not load in time before I click on the search and search the same college, the college is not hearted.

2. I use the filters but I do not heart a college just yet. I go to the dashboard, then I do a quick search then I heart the college that comes up on the search. I then click on the explore page. The college is one of the colleges I had filtered for previously so it shows up in the filtered results, but it is not hearted on the explore page. If you click back on the dashboard and DO NOT let it load in time to show your colleges and instead click back on the explore page, the college is not hearted. IF you do allow the dashboard to load all your colleges then you go back to the explore page, the college is hearted.

3. Same thing as 2 but instead of going to the dashboard, go to the essays tab.

Note that these problems do not happen when I did not filter by anything.

**Comment by keskinmbaha** [comment]
Overall there seems to be a problem with the site not loading fast enough to update everything related to one college. Also, seems to be a problem with a college not staying hearted when the users filters had not been cleared.

**Comment by skaiwu** [comment]
should be fixed
