### ISSUE TITLE
Removing One College From Many in Dashboard

### ISSUE THREAD

**Issue by keskinmbaha** [ashwinxkumar01/apps-college#49]
When removing one college from many, the checkbox stays in the greyed out form with the white line through it even though no college's check boxes have been selected.

**Comment by skaiwu** [comment]
stop i responded to you on snap

**Comment by keskinmbaha** [comment]
Bruh this is a different issue. I did not mention this issue on the previous If you resolved this one as well, say so please.

**Comment by skaiwu** [comment]
thank you

**Comment by ashwinxkumar01** [comment]
Push before closing issue... someone else besides you has to verify closing issues and that it works
